// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48r_q2RuB3GnhRsSxsAo9UUWgxZu6BdA',
    appId: '1:721990517516:web:fb759ad0bc66fb301f7f29',
    messagingSenderId: '721990517516',
    projectId: 'dynamic-reef-413004',
    authDomain: 'dynamic-reef-413004.firebaseapp.com',
    storageBucket: 'dynamic-reef-413004.appspot.com',
    measurementId: 'G-VVSB8XFCGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJuIcOw_oNsBSikU4WJEEwTrLQEyRoeS4',
    appId: '1:721990517516:android:bc713c433490452d1f7f29',
    messagingSenderId: '721990517516',
    projectId: 'dynamic-reef-413004',
    storageBucket: 'dynamic-reef-413004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZiylU9MhipHOB2CHctNMHpOvrQ1Dtyk',
    appId: '1:721990517516:ios:3d5cf5b0208378041f7f29',
    messagingSenderId: '721990517516',
    projectId: 'dynamic-reef-413004',
    storageBucket: 'dynamic-reef-413004.appspot.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZiylU9MhipHOB2CHctNMHpOvrQ1Dtyk',
    appId: '1:721990517516:ios:369256dbd7a3e1721f7f29',
    messagingSenderId: '721990517516',
    projectId: 'dynamic-reef-413004',
    storageBucket: 'dynamic-reef-413004.appspot.com',
    iosBundleId: 'com.example.tiktok.RunnerTests',
  );
}
